### PR TITLE
Improved Readme

### PR DESCRIPTION
**Pull request by c0de-fox**
I've added the following information, which should prove greatly benificial to anyone just getting started with the project:
* Instructions for installing new firmware onto the device
* Links to the libraries used in the examples - Or what I believe to be the correct libraries
* Instructions for patching `i2cdev` and `mpu6050` libraries as they give compile errors otherwise

### CODE REVIEW

**Comment by chunkysteveo** [comment]
Love it... keep forgetting this is GIT and I could submit my own suggestions! Took a while to figure out the buffer issue and which board to use. I have a couple of useful demos too, but worried that with only ~100 unit if it was worth adding a lot of user support?

**Comment by c0de-fox** [comment]
I'm of the opinion that the more demos, the better, especially if they add new functionality such as using the onboard wifi/bluetooth, or connecting to a polling server for example. More general purpose libraries might be useful too, but Adafruit's DotStar libraries are pretty rich, so idk.

Also while only ~100 assembled units exist, Sean provided the board files and the BOM, so I'd expect some adventurous hackers might want to make their own. That, plus this is derived from Adafruit Feather (in that they share the same pinout), perhaps those examples might be a little cross-compatible.

I for one will be submitting another PR with some examples similar to what I described above, once I actually make them that is! x3

**Comment by chunkysteveo** [comment]
Sounds great! Have had some FASTLED examples working too just to test the pixels and they work great too.

**Review by seanhodgins — APPROVED** [review]
Looks good. Sorry I took so long, I'm not used to people submitting pull requests!

**Pull request merged**
